import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync, existsSync } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// Create dist directory structure
const distDir = 'dist/obsidian-photos-bridge-plugin';
if (!existsSync('dist')) {
    mkdirSync('dist');
}
if (!existsSync(distDir)) {
    mkdirSync(distDir, { recursive: true });
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: `${distDir}/main.js`,
});

// Copy required files to dist directory
function copyRequiredFiles() {
    try {
        // Copy manifest.json
        copyFileSync('manifest.json', `${distDir}/manifest.json`);
        console.log('✅ Copied manifest.json');
        
        // Copy styles.css
        copyFileSync('styles.css', `${distDir}/styles.css`);
        console.log('✅ Copied styles.css');
        
        // Copy versions.json if exists
        if (existsSync('versions.json')) {
            copyFileSync('versions.json', `${distDir}/versions.json`);
            console.log('✅ Copied versions.json');
        }
        
        // Copy README.md
        if (existsSync('README.md')) {
            copyFileSync('README.md', `${distDir}/README.md`);
            console.log('✅ Copied README.md');
        }
        
        console.log('');
        console.log('🎯 Plugin distribution created at:', distDir);
        console.log('📁 Ready to copy to Obsidian plugins directory!');
        console.log('');
        console.log('📋 Installation steps:');
        console.log('   1. Copy the entire "obsidian-photos-bridge-plugin" folder');
        console.log('   2. Paste it into: <your-vault>/.obsidian/plugins/');
        console.log('   3. Enable the plugin in Obsidian Settings > Community Plugins');
        console.log('');
        
    } catch (error) {
        console.error('❌ Error copying files:', error);
    }
}

if (prod) {
	await context.rebuild();
	copyRequiredFiles();
	process.exit(0);
} else {
	await context.watch();
} 